spring:
  application:
    name: goormitrip

  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: user
      password: goormi123@
