spring:
  application:
    name: goormitrip
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname, profile_image
            client-name: Kakao

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 1800000