spring:
  application:
    name: goormitrip
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 1800000